# Generated by Django 5.2.5 on 2025-08-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("txt", models.TextField(max_length=7000)),
                ("is_enable", models.BooleanField(default=False)),
                ("publish_date", models.DateField()),
                ("created_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
            ],
        ),
    ]
