# Generated by Django 5.2.5 on 2025-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
