# Generated by Django 5.2.5 on 2025-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_created_time_alter_post_publish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
